name: Update README with Repos

on:
  workflow_dispatch:  # Habilita la ejecución manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Script
        run: echo "Workflow ejecutado correctamente"
